### ISSUE TITLE
Git protocol in bower.json

### ISSUE THREAD

**Issue by tdavisjr** [shawnwildermuth/WilderBlog#12]
I forked the project and tried to restore the bower packages. Bootstrap failed since it was using the git protocol to pull down the v4-dev branch. I'm guessing my enterprise blocks this protocol and perhaps you can consider using https instead. I was able to get up and running after this change. Maybe there are others like me that are locked down at work.

**Comment by shawnwildermuth** [comment]
Didn't think of that. Can you do a PR for that?
