### ISSUE TITLE
Build: Cannot find name 'Map'.

### ISSUE THREAD

**Issue by MaherJendoubi** [shawnwildermuth/WilderBlog#15]
![image](https://cloud.githubusercontent.com/assets/1798510/15264013/2c1c683e-196f-11e6-8606-def139d8627e.png)

**Comment by shawnwildermuth** [comment]
Will look, might be a problem with getting the Angular.d.ts file.

**Comment by MaherJendoubi** [comment]
@shawnwildermuth Is it possible to upgrade to angular rc1 please?

Thanks.

**Comment by shawnwildermuth** [comment]
Feel free and send me a Pull Request. It will get fixed eventually, but not high on my priority at the moment.

**Comment by MaherJendoubi** [comment]
@shawnwildermuth Done. Please have a look on https://github.com/shawnwildermuth/WilderBlog/pull/16

**Comment by shawnwildermuth** [comment]
Thanks for the help! I'll look at the PR this evening.

**Comment by MaherJendoubi** [comment]
Great! I'm looking forward to hearing your feedback.

**Comment by shawnwildermuth** [comment]
I've removed Angular from the project.
