### ISSUE TITLE
EF Core RC2. Set the maxLength parameter of some columns in the Identity DB migration

### ISSUE THREAD

**Issue by MrGlenThomas** [shawnwildermuth/WilderBlog#19]
I had to set the maxLength parameter of some columns in the Identity DB migration because it was throwing a SqlException when using EF Core RC2.

```
NormalizedName = table.Column<string>(nullable: true, maxLength: 256)
...
NormalizedEmail = table.Column<string>(nullable: true, maxLength: 256),
NormalizedUserName = table.Column<string>(nullable: true, maxLength: 256),
```

See [RC2 => RTM maxLength needs to be added to existing migrations](https://github.com/aspnet/Announcements/issues/195)

I could push changes, but am very new to GitHub and still not sure how the whole system works. It says I don't have permissions and I'm guessing that means  that your repo is closed to push from public sources...

**Comment by shawnwildermuth** [comment]
I rebuilt the migrations when I upgraded to RTM so that they are fixed already. Try upgrading to RTM instead of using RC2.

**Comment by MrGlenThomas** [comment]
I _think_ I might've already been on RTM.

When I run `dotnet --version` it says 

> 1.0.0-preview2-003121

All of the versions in my project.json are either 1.0.0 or 1.0.0-preview2-final
