### ISSUE TITLE
Missing JavaScript libraries on Contact page?

### ISSUE THREAD

**Issue by MrGlenThomas** [shawnwildermuth/WilderBlog#20]
This _might not_ be an issue as I am a beginner in web dev, but there seems to be some JavaScript packages missing from wwwroot/lib that are used by the Contact page.

I see that these libraries are node dependencies and so I expect that they are required server side, but the contact page seems to reference them as if they should be available in wwwroot and the lack of their presence seems to stop the contact page from working as it should. I have tried adding them as bower dependencies but can't find them in bower. Is there a Bower packages that needs to be added?

These are the missing libraries:

```
<script src="~/lib/core-js/shim.js"></script>
<script src="~/lib/zone.js/zone.js"></script>
<script src="~/lib/reflect-metadata/Reflect.js"></script>
<script src="~/lib/systemjs/system.src.js"></script>
<script src="~/app/systemjs.config.js"></script>
```

**Comment by shawnwildermuth** [comment]
The files are copied to lib on deployment. If you need them locally, just "npm install" then "gulp".

**Comment by MrGlenThomas** [comment]
I had done the npm install, but didn't realise that I needed to run gulp. Thanks!
