### ISSUE TITLE
You're using an old .NET Core SDK that is not included in VS 2017 out of the box

### ISSUE THREAD

**Issue by ststeiger** [shawnwildermuth/WilderBlog#24]
You're using an old .NET Core SDK. Probably a preview-version that you manually installed. 
Visual Studio 2017 15.3/15.4 doesn't have your SDK-version installed, so the projects don't load. 

Your Global.json has version 1.0.4
`"version": "1.0.4"`

Upgrade, and change this to: 
```
{
  "projects": [ "src" ],
  "sdk": {
    "version": "1.1.0"
  }
}

```

for the projects to work in Visual Studio 2017 out of the box.

**Comment by shawnwildermuth** [comment]
Changed to 2.0
