### ISSUE TITLE
Specified lodash-version doesn't exist in Bower

### ISSUE THREAD

**Issue by ststeiger** [shawnwildermuth/WilderBlog#29]
In https://github.com/shawnwildermuth/WilderBlog/blob/master/src/WilderBlog/bower.json
you specify `"lodash": "4.8.2". `

But there is no lodash 4.8.2 in the bower repositorys, at least none that visual studio can find. 
Bower only has 4.16.* and 4.17.*

**Comment by shawnwildermuth** [comment]
Fixed.
