### ISSUE TITLE
The partial view '_Info' was not found.

### ISSUE THREAD

**Issue by ststeiger** [shawnwildermuth/WilderBlog#31]
Running the current master on Linux yields the following error

```
An unhandled exception occurred while processing the request.
InvalidOperationException: The partial view '_Info' was not found. The following locations were searched:
/Views/Root/_Info.cshtml
/Views/Shared/_Info.cshtml
```
File 
WilderBlog/src/WilderBlog/Views/Shared/_info.cshtml
should be called 
WilderBlog/src/WilderBlog/Views/Shared/_Info.cshtml
(note: capital i in info).

Or make it lowercase where you reference it. 
Maybe _inlineAd.cshtml might have the same problem.

**Comment by shawnwildermuth** [comment]
Ah, the dredded case sensitive file systems. Will fix.

**Comment by shawnwildermuth** [comment]
Fixed.
