### ISSUE TITLE
web resource file can't find

### ISSUE THREAD

**Issue by qinxiaowen** [shawnwildermuth/WilderBlog#32]
when i use task runner run task to build web resource files ,i find these find copy to /vendor/ folder,but when i run the project,request resource folder is /lib/,so Did I miss any of the steps?
![2018-03-20 14_07_41-developer tools - http___localhost_5000_](https://user-images.githubusercontent.com/8536046/37638524-4e90fe14-2c48-11e8-99c2-e97d521d7b72.png)

**Comment by shawnwildermuth** [comment]
In my move from bower to npm, I forgot to change these names. Try again with latest.
