### ISSUE TITLE
Cannot update db

### ISSUE THREAD

**Issue by saigkill** [shawnwildermuth/WilderBlog#37]
Currently i'm trying to move my blog to Azure. I created a new db in Azure and placed the credentials in my config.Production.json.
The codebase is placed there: https://github.com/saigkill/WilderBlog

Currently i'm getting:

PS C:\Users\Sasch\source\repos\WilderBlog\src\WilderBlog.Data> dotnet ef database update
Build started...
Build succeeded.
Unable to create an object of type 'WilderContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

**Comment by shawnwildermuth** [comment]
Do it in the WilderBlog project, not the Data project.

**Comment by saigkill** [comment]
Thanks that works perfectly :-)
