### ISSUE TITLE
Extra unnecessary horizontal scrolling

### ISSUE THREAD

**Issue by ZaarourOmar** [shawnwildermuth/WilderBlog#64]
The website has unnecessary extra width. This red area shows up when I'm scrolling vertically

![Screenshot_20210305_142132_com android chrome](https://user-images.githubusercontent.com/6832511/110175023-4e8c2e00-7dbe-11eb-8d96-f3c619ba809a.jpg)

**Comment by shawnwildermuth** [comment]
Chrome on Android? Do you know your browser version so I can replicate?

**Comment by ZaarourOmar** [comment]
Using Chrome on Android

**Comment by ZaarourOmar** [comment]
Not on main page, only when I'm reading an article

**Comment by shawnwildermuth** [comment]
Great catch. Fixing now.

**Comment by ZaarourOmar** [comment]
I think same issue is affecting the fields on the contact me page as well

**Comment by shawnwildermuth** [comment]
Found and fixed.

**Comment by ZaarourOmar** [comment]
Confirmed on my end.

**Comment by shawnwildermuth** [comment]
Confirmed fixed?

**Comment by ZaarourOmar** [comment]
Yes

**Comment by shawnwildermuth** [comment]
Closing issue as fixed.
